version: 2
jobs:
  build:
    docker:
      - image: docker:edge-git
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache bash
      - run: echo 'export PATH="/app/make:$PATH"' >> $BASH_ENV
      - restore_cache:
          key: hello-{{ .Branch }}
          paths:
            - /tmp/docker-cache
      - run: |
          if [[ -f /tmp/docker-cache/hello ]]; then
            cat /tmp/docker-cache/hello
          fi
      - run: |
          mkdir -p /tmp/docker-cache
          echo "Bonjour $CIRCLE_BUILD_NUM" >> /tmp/docker-cache/hello
      - run: |
          cat /tmp/docker-cache/hello
      - save_cache:
          key: hello-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/docker-cache
